import { ButtonV2, Checkbox } from "@/components";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import allImgPaths from "../../assets";

const index = () => {
  const navigate = useNavigate();
  const [isChecked, setIsChecked] = useState(false);
  return (
    <div className="w-full h-screen flex flex-col justify-center items-center bg-white shadow-customShadow1 bg-dots">
      <div className="rounded-3xl border border-secondary-200 px-11 pt-8 bg-white w-full max-w-[718px] mx-auto mb-11 select-none">
        <div className="bg-tertiary-50/50 rounded-2xl px-6 py-6 mb-6">
          <h2 className="text-[32px] text-primary-900 font-bold pb-5">
            <span className="text-[32px] text-primary-900 font-bold italic">
              Welcome to
            </span>{" "}
            AthenaPro
          </h2>
          <p className="text-xl text-black font-medium pb-1">
            Use of AI Application
          </p>
          <p className="text-tertiary-900 text-base font-normal">
            This AI application for sales is designed to assist users in
            optimizing their sales strategies and improving customer engagement.
            However, the use of this application is subject to the following
            terms and conditions:
          </p>
        </div>

        <div className="bg-tertiary-50/50 rounded-2xl px-6 py-6 overflow-y-auto max-h-[calc(100vh_-_540px)]">
          <div className="mb-8 last:mb-0">
            <div className="flex items-center gap-x-2 mb-2">
              <img className="w-5 h-5" src={allImgPaths.lock} alt="" />
              <p className="text-xl text-tertiary-900 font-semibold leading-none">
                No Guarantees of Success
              </p>
            </div>
            <p className="text-tertiary-900 text-base font-normal">
              This AI application for sales is designed to assist users in
              optimizing their sales strategies and improving customer
              engagement. However, the use of this application is subject to the
              following terms and conditions:
            </p>
          </div>

          <div className="mb-8 last:mb-0">
            <div className="flex items-center gap-x-2 mb-2">
              <img className="w-5 h-5" src={allImgPaths.lock} alt="" />
              <p className="text-xl text-tertiary-900 font-semibold leading-none">
                Data Accuracy
              </p>
            </div>
            <p className="text-tertiary-900 text-base font-normal">
              The AI's recommendations rely on the quality and completeness of
              user-provided data. Inaccurate or incomplete data can affect the
              outputs generated by the AI.
            </p>
          </div>

          <div className="mb-8 last:mb-0">
            <div className="flex items-center gap-x-2 mb-2">
              <img className="w-5 h-5" src={allImgPaths.lock} alt="" />
              <p className="text-xl text-tertiary-900 font-semibold leading-none">
                User Responsibility
              </p>
            </div>
            <p className="text-tertiary-900 text-base font-normal">
              Users must use the AI application's information responsibly,
              exercising their own judgment when implementing strategies. The
              application serves as a decision-making tool, not a definitive
              guide.
            </p>
          </div>

          <div className="mb-8 last:mb-0">
            <div className="flex items-center gap-x-2 mb-2">
              <img className="w-5 h-5" src={allImgPaths.lock} alt="" />
              <p className="text-xl text-tertiary-900 font-semibold leading-none">
                Compliance with Laws
              </p>
            </div>
            <p className="text-tertiary-900 text-base font-normal">
              Users must ensure their use of the AI application complies with
              all applicable laws and regulations. It should not be used for
              illegal or unethical purposes.
            </p>
          </div>

          <div className="mb-8 last:mb-0">
            <div className="flex items-center gap-x-2 mb-2">
              <img className="w-5 h-5" src={allImgPaths.lock} alt="" />
              <p className="text-xl text-tertiary-900 font-semibold leading-none">
                Privacy and Security
              </p>
            </div>
            <p className="text-tertiary-900 text-base font-normal">
              User data is processed according to our privacy policy. While we
              take measures to protect data, users should also take precautions
              to safeguard their information and systems.
            </p>
          </div>

          <div className="mb-8 last:mb-0">
            <div className="flex items-center gap-x-2 mb-2">
              <img className="w-5 h-5" src={allImgPaths.lock} alt="" />
              <p className="text-xl text-tertiary-900 font-semibold leading-none">
                Handling Sensitive Information
              </p>
            </div>
            <p className="text-tertiary-900 text-base font-normal">
              Avoid inputting sensitive or personally identifiable information
              (PII) unless necessary. This includes social security numbers,
              credit card details, and confidential business information.
              Exercise caution with sensitive data.
            </p>
          </div>

          <div className="mb-8 last:mb-0">
            <div className="flex items-center gap-x-2 mb-2">
              <img className="w-5 h-5" src={allImgPaths.lock} alt="" />
              <p className="text-xl text-tertiary-900 font-semibold leading-none">
                Limitation of Liability
              </p>
            </div>
            <p className="text-tertiary-900 text-base font-normal">
              We are not liable for any damages arising from the use or
              inability to use the AI application. Users assume full
              responsibility for associated risks.
            </p>
          </div>

          <div className="mb-8 last:mb-0">
            <div className="flex items-center gap-x-2 mb-2">
              <img className="w-5 h-5" src={allImgPaths.lock} alt="" />
              <p className="text-xl text-tertiary-900 font-semibold leading-none">
                Modifications and Updates
              </p>
            </div>
            <p className="text-tertiary-900 text-base font-normal">
              The AI application may be periodically updated or modified to
              improve functionality. Users are responsible for staying informed
              about updates and adapting their usage accordingly.
            </p>
          </div>

          <div className="mb-8 last:mb-0">
            <div className="flex items-center gap-x-2 mb-2">
              <img className="w-5 h-5" src={allImgPaths.lock} alt="" />
              <p className="text-xl text-tertiary-900 font-semibold leading-none">
                Third-Party Integrations
              </p>
            </div>
            <p className="text-tertiary-900 text-base font-normal">
              The AI application may integrate with third-party services. We are
              not responsible for the practices or policies of these services.
              Review third-party terms and conditions before use.
            </p>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-[48px] border border-secondary-200 py-3.5 px-8 w-full max-w-[718px] mx-auto flex">
        <label
          htmlFor="getting"
          className="flex items-center gap-x-3 w-1/2 cursor-pointer select-none"
        >
          <Checkbox
            id="getting"
            onChange={() => setIsChecked((prev) => !prev)}
            checked={isChecked}
          />
          <p className="text-base text-tertiary-900 font-medium">
            Agree to this disclaimer and the associated terms and conditions.
          </p>
        </label>
        <div className="w-1/2">
          <ButtonV2
            rightIcon={allImgPaths.rightArrow}
            className="w-full"
            onClick={() => {
              navigate("/chats");
            }}
          >
            Get Started
          </ButtonV2>
        </div>
      </div>
    </div>
  );
};

export default index;
